FROM elasticsearch:5.2.0

ADD config/es-cluster/elasticsearch.yml /usr/share/elasticsearch/config/
USER root
RUN chown elasticsearch:elasticsearch config/elasticsearch.yml \
&& mkdir /usr/share/elasticsearch/data/nodes \
&& mkdir /usr/share/elasticsearch/data/nodes/1 \
&& chown elasticsearch:elasticsearch /usr/share/elasticsearch/data/nodes/1
USER elasticsearch