network.host: 0.0.0.0

# this value is required because we set "network.host"
# be sure to modify it appropriately for a production cluster deployment
discovery.zen.minimum_master_nodes: 1
# bootstrap.memory_lock: true

discovery.zen.ping.unicast.hosts: ["edc_ingest", "edc_elastic",  "edc_data"]

cluster.name: valcri
node.max_local_storage_nodes: 5
cluster.routing.allocation.enable: all